var arr = [1, 2, 3]

console.log("arr =", arr)
console.log("map():", arr.map(x => x*2))
console.log("filter():", arr.filter(x => x < 3))
console.log("indexOf():", arr.indexOf(2))
console.log("reduce():", arr.reduce((x, y) => x*y))
console.log("concat():", arr.concat([4, 5, 6]))
console.log("slice():", arr.slice(1))
console.log("join():", arr.join('-'))
console.log("lastIndexOf():", arr.lastIndexOf(3))
console.log("find():", arr.find(x => x > 2))
console.log("findIndex():", arr.findIndex(x => x > 2))
console.log("includes():", arr.includes(2))
console.log("some():", arr.some(x => x % 2 == 0))
console.log("forEach():") 
arr.forEach(x => console.log(x))
console.log("every():", arr.every(x => x < 5))

console.log("push(): in-place:")
arr.push(4)
console.log("pop(): in-place:")
arr.pop(4)
console.log("shift(): in-place:")
arr.shift()
console.log("unshift(): in-place:")
arr.unshift(1)
arr.splice(1, 0, 4)
console.log("splice(): in-place:", arr)
console.log("reverse(): in-place:", arr.reverse())
// fill with 0 from position 2 until position 3
console.log("fill(): in-place:", arr.fill(0, 0, 3))
